"""
CollectionTheme model for LLM-powered clustered themes.

Each row represents a discovered theme within a collection,
generated by embedding-based clustering + LLM labeling.
"""
import uuid
from datetime import datetime
from sqlalchemy import Column, String, DateTime, Text, Float, ForeignKey
from sqlalchemy.dialects.postgresql import UUID, JSONB, ARRAY
from sqlalchemy.orm import relationship

from app.db.base import Base


class CollectionTheme(Base):
    """A clustered theme discovered within a collection."""

    __tablename__ = "collection_themes"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    collection_id = Column(
        UUID(as_uuid=True),
        ForeignKey("collections.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    theme_label = Column(String(255), nullable=False)
    theme_description = Column(Text, nullable=True)
    video_ids = Column(JSONB, nullable=False, default=[])
    relevance_score = Column(Float, nullable=True)
    topic_keywords = Column(ARRAY(Text), nullable=False, default=[])

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(
        DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False
    )

    # Relationships
    collection = relationship("Collection")

    def __repr__(self):
        return f"<CollectionTheme(id={self.id}, label={self.theme_label})>"
