"""
Pydantic schemas for API request/response validation.
"""
from app.schemas.video import (
    VideoIngestRequest,
    VideoIngestResponse,
    VideoMetadata,
    VideoStatus,
    VideoDetail,
    VideoList,
    VideoDeleteRequest,
    VideoDeleteResponse,
    VideoDeleteBreakdown,
    VideoCancelRequest,
    VideoCancelResponse,
    CleanupSummary,
    BulkCancelRequest,
    BulkCancelResponse,
    BulkCancelResultItem,
)
from app.schemas.job import (
    JobStatus,
    JobDetail,
)
from app.schemas.transcript import (
    TranscriptDetail,
    TranscriptSegment,
)
from app.schemas.conversation import (
    ConversationCreateRequest,
    ConversationUpdateRequest,
    MessageSendRequest,
    ChunkReference,
    Message,
    MessageWithReferences,
    ConversationDetail,
    ConversationWithMessages,
    ConversationList,
    MessageResponse,
    ConversationSource,
    ConversationSourcesResponse,
    ConversationSourcesUpdateRequest,
)
from app.schemas.collection import (
    CollectionCreateRequest,
    CollectionUpdateRequest,
    CollectionAddVideosRequest,
    VideoUpdateTagsRequest,
    CollectionVideoInfo,
    CollectionSummary,
    CollectionDetail,
    CollectionList,
    VideoWithCollections,
)
from app.schemas.usage import (
    UsageSummary,
    StorageBreakdown,
    UsageCounts,
    VectorStoreStat,
    QuotaStat,
)
from app.schemas.insights import (
    ConversationInsightsResponse,
    TopicChunksResponse,
)
from app.schemas.admin import (
    UserSummary,
    UserListResponse,
    UserDetailMetrics,
    UserCostBreakdown,
    UserDetail,
    UserUpdateRequest,
    QuotaOverrideRequest,
    AdminNoteCreateRequest,
    AdminNote,
    SystemStats,
    UserEngagementStats,
    DashboardResponse,
    UserActivityLog,
    UserActivityResponse,
    UserErrorLog,
    UserErrorResponse,
    AbuseAlert,
    AbuseAlertResponse,
    QAFeedItem,
    QAFeedResponse,
    AuditLogItem,
    AuditLogResponse,
    QASource,
    ConversationMessage,
    ConversationSummary,
    ConversationListResponse,
    ConversationDetailResponse,
    AdminVideoItem,
    AdminVideoOverview,
    AdminCollectionOverview,
    ContentOverviewResponse,
)
from app.schemas.subscription import (
    SubscriptionTier,
    SubscriptionStatus,
    SubscriptionCreate,
    SubscriptionUpdate,
    SubscriptionDetail,
    CheckoutSessionRequest,
    CheckoutSessionResponse,
    CustomerPortalRequest,
    CustomerPortalResponse,
    QuotaUsage,
    PricingTier,
)

__all__ = [
    # Video
    "VideoIngestRequest",
    "VideoIngestResponse",
    "VideoMetadata",
    "VideoStatus",
    "VideoDetail",
    "VideoList",
    "VideoDeleteRequest",
    "VideoDeleteResponse",
    "VideoDeleteBreakdown",
    "VideoCancelRequest",
    "VideoCancelResponse",
    "CleanupSummary",
    "BulkCancelRequest",
    "BulkCancelResponse",
    "BulkCancelResultItem",
    # Transcript
    "TranscriptDetail",
    "TranscriptSegment",
    # Job
    "JobStatus",
    "JobDetail",
    # Conversation
    "ConversationCreateRequest",
    "ConversationUpdateRequest",
    "MessageSendRequest",
    "ChunkReference",
    "Message",
    "MessageWithReferences",
    "ConversationDetail",
    "ConversationWithMessages",
    "ConversationList",
    "MessageResponse",
    "ConversationSource",
    "ConversationSourcesResponse",
    "ConversationSourcesUpdateRequest",
    # Collection
    "CollectionCreateRequest",
    "CollectionUpdateRequest",
    "CollectionAddVideosRequest",
    "VideoUpdateTagsRequest",
    "CollectionVideoInfo",
    "CollectionSummary",
    "CollectionDetail",
    "CollectionList",
    "VideoWithCollections",
    # Usage
    "UsageSummary",
    "StorageBreakdown",
    "UsageCounts",
    "VectorStoreStat",
    "QuotaStat",
    # Insights
    "ConversationInsightsResponse",
    "TopicChunksResponse",
    # Admin
    "UserSummary",
    "UserListResponse",
    "UserDetailMetrics",
    "UserCostBreakdown",
    "UserDetail",
    "UserUpdateRequest",
    "QuotaOverrideRequest",
    "AdminNoteCreateRequest",
    "AdminNote",
    "SystemStats",
    "UserEngagementStats",
    "DashboardResponse",
    "UserActivityLog",
    "UserActivityResponse",
    "UserErrorLog",
    "UserErrorResponse",
    "AbuseAlert",
    "AbuseAlertResponse",
    "QAFeedItem",
    "QAFeedResponse",
    "AuditLogItem",
    "AuditLogResponse",
    "QASource",
    "ConversationMessage",
    "ConversationSummary",
    "ConversationListResponse",
    "ConversationDetailResponse",
    "AdminVideoItem",
    "AdminVideoOverview",
    "AdminCollectionOverview",
    "ContentOverviewResponse",
    # Subscription
    "SubscriptionTier",
    "SubscriptionStatus",
    "SubscriptionCreate",
    "SubscriptionUpdate",
    "SubscriptionDetail",
    "CheckoutSessionRequest",
    "CheckoutSessionResponse",
    "CustomerPortalRequest",
    "CustomerPortalResponse",
    "QuotaUsage",
    "PricingTier",
]
